# Generated by Django 5.2.7 on 2026-01-18 04:28

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RutaSenderismo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('distance', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('Fácil', 'Fácil'), ('Medio', 'Medio'), ('Difícil', 'Difícil')], max_length=10)),
                ('image', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('pública', 'Pública'), ('privada', 'Privada'), ('agroturismo', 'Agroturismo')], max_length=20)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(choices=[('senderismo', 'Senderismo'), ('agroturismo', 'Agroturismo')], max_length=20)),
                ('description', models.TextField()),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rutas_senderismo',
                'ordering': ['-created_at'],
            },
        ),
    ]
