# Generated by Django 5.2.7 on 2026-01-18 05:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='routes.rutasenderismo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ruta_ratings',
                'unique_together': {('ruta', 'user')},
            },
        ),
    ]
