# Generated by Django 5.2.7 on 2026-02-17 04:02

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_rutarating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Fecha de la excursión')),
                ('available_slots', models.PositiveIntegerField(help_text='Cupos disponibles para esta fecha')),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='Si está disponible para reservas esta fecha')),
                ('notes', models.TextField(blank=True, help_text='Notas especiales para esta fecha (ej: clima, eventos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'db_table': 'ruta_availabilities',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='RutaImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.CharField(help_text='URL de la imagen', max_length=500)),
                ('caption', models.CharField(blank=True, help_text='Descripción de la imagen', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen de Ruta',
                'verbose_name_plural': 'Imágenes de Rutas',
                'db_table': 'ruta_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='rutarating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='rutasenderismo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ruta de Senderismo', 'verbose_name_plural': 'Rutas de Senderismo'},
        ),
        migrations.AddField(
            model_name='rutarating',
            name='comment',
            field=models.TextField(blank=True, help_text='Comentario opcional sobre la experiencia'),
        ),
        migrations.AddField(
            model_name='rutarating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rutasenderismo',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio base por persona en COP', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='rutasenderismo',
            name='included_services',
            field=models.TextField(blank=True, help_text='Servicios incluidos en el precio (separados por líneas)'),
        ),
        migrations.AddField(
            model_name='rutasenderismo',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Si la ruta está disponible para reservas'),
        ),
        migrations.AddField(
            model_name='rutasenderismo',
            name='max_capacity',
            field=models.PositiveIntegerField(default=20, help_text='Capacidad máxima de personas por excursión', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rutasenderismo',
            name='max_participants_per_booking',
            field=models.PositiveIntegerField(default=10, help_text='Máximo de participantes por reserva individual', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rutasenderismo',
            name='min_participants',
            field=models.PositiveIntegerField(default=1, help_text='Mínimo de participantes requeridos por reserva', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rutasenderismo',
            name='requirements',
            field=models.TextField(blank=True, help_text='Requisitos para los participantes'),
        ),
        migrations.AddField(
            model_name='rutasenderismo',
            name='requires_date_selection',
            field=models.BooleanField(default=True, help_text='Si se debe seleccionar fecha específica para la excursión'),
        ),
        migrations.AddField(
            model_name='rutasenderismo',
            name='requires_payment',
            field=models.BooleanField(default=False, help_text='Si la ruta requiere pago previo para reservar'),
        ),
        migrations.AddField(
            model_name='rutasenderismo',
            name='what_to_bring',
            field=models.TextField(blank=True, help_text='Qué deben llevar los participantes'),
        ),
        migrations.AlterField(
            model_name='rutarating',
            name='score',
            field=models.PositiveSmallIntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='rutasenderismo',
            name='category',
            field=models.CharField(choices=[('senderismo', 'Senderismo'), ('agroturismo', 'Agroturismo')], help_text='Categoría de la ruta', max_length=20),
        ),
        migrations.AlterField(
            model_name='rutasenderismo',
            name='company',
            field=models.CharField(blank=True, help_text='Empresa u organización a cargo', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rutasenderismo',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Coordenadas GPS del punto de inicio', srid=4326),
        ),
        migrations.AlterField(
            model_name='rutasenderismo',
            name='description',
            field=models.TextField(help_text='Descripción detallada de la ruta'),
        ),
        migrations.AlterField(
            model_name='rutasenderismo',
            name='difficulty',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Medio', 'Medio'), ('Difícil', 'Difícil')], help_text='Nivel de dificultad', max_length=10),
        ),
        migrations.AlterField(
            model_name='rutasenderismo',
            name='distance',
            field=models.CharField(help_text='Distancia total (ej: 5.2 km)', max_length=50),
        ),
        migrations.AlterField(
            model_name='rutasenderismo',
            name='duration',
            field=models.CharField(help_text='Duración estimada (ej: 3-4 horas)', max_length=50),
        ),
        migrations.AlterField(
            model_name='rutasenderismo',
            name='email',
            field=models.EmailField(help_text='Email de contacto', max_length=254),
        ),
        migrations.AlterField(
            model_name='rutasenderismo',
            name='image',
            field=models.CharField(help_text='URL de la imagen principal', max_length=255),
        ),
        migrations.AlterField(
            model_name='rutasenderismo',
            name='location',
            field=models.CharField(help_text='Ubicación de la ruta', max_length=200),
        ),
        migrations.AlterField(
            model_name='rutasenderismo',
            name='phone',
            field=models.CharField(help_text='Teléfono de contacto', max_length=20),
        ),
        migrations.AlterField(
            model_name='rutasenderismo',
            name='title',
            field=models.CharField(help_text='Nombre de la ruta', max_length=200),
        ),
        migrations.AlterField(
            model_name='rutasenderismo',
            name='type',
            field=models.CharField(choices=[('pública', 'Pública'), ('privada', 'Privada'), ('agroturismo', 'Agroturismo')], help_text='Tipo de ruta', max_length=20),
        ),
        migrations.AlterField(
            model_name='rutasenderismo',
            name='whatsapp',
            field=models.CharField(help_text='Número de WhatsApp', max_length=20),
        ),
        migrations.AddIndex(
            model_name='rutarating',
            index=models.Index(fields=['ruta', 'score'], name='ruta_rating_ruta_id_537902_idx'),
        ),
        migrations.AddIndex(
            model_name='rutarating',
            index=models.Index(fields=['created_at'], name='ruta_rating_created_a25bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='rutasenderismo',
            index=models.Index(fields=['requires_payment', 'is_active'], name='rutas_sende_require_0835ff_idx'),
        ),
        migrations.AddIndex(
            model_name='rutasenderismo',
            index=models.Index(fields=['category', 'type'], name='rutas_sende_categor_be8f82_idx'),
        ),
        migrations.AddIndex(
            model_name='rutasenderismo',
            index=models.Index(fields=['is_active', 'created_at'], name='rutas_sende_is_acti_0cbc2a_idx'),
        ),
        migrations.AddField(
            model_name='rutaavailability',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='routes.rutasenderismo'),
        ),
        migrations.AddField(
            model_name='rutaimage',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='routes.rutasenderismo'),
        ),
        migrations.AddIndex(
            model_name='rutaavailability',
            index=models.Index(fields=['ruta', 'date'], name='ruta_availa_ruta_id_0c5bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='rutaavailability',
            index=models.Index(fields=['date', 'is_available'], name='ruta_availa_date_a1331a_idx'),
        ),
        migrations.AddIndex(
            model_name='rutaavailability',
            index=models.Index(fields=['is_available', 'date'], name='ruta_availa_is_avai_2b200d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rutaavailability',
            unique_together={('ruta', 'date')},
        ),
        migrations.AddIndex(
            model_name='rutaimage',
            index=models.Index(fields=['ruta', 'order'], name='ruta_images_ruta_id_d431e0_idx'),
        ),
    ]
