# Generated by Django 5.2.7 on 2026-01-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rutasenderismo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RutaSenderismo',
        ),
    ]
