# Generated by Django 5.2.7 on 2026-02-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='correo_electronico_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
