# Generated by Django 5.2.7 on 2026-02-17 04:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0003_rutaavailability_rutaimage_alter_rutarating_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('BOOKING', 'Reserva de Ruta'), ('SUBSCRIPTION', 'Suscripción'), ('AGROTURISMO', 'Agroturismo')], default='BOOKING', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto total en COP', max_digits=10, null=True)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('DECLINED', 'Rechazado'), ('ERROR', 'Error'), ('VOIDED', 'Anulado')], db_index=True, default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('PSE', 'PSE'), ('CARD', 'Tarjeta'), ('NEQUI', 'Nequi'), ('BANCOLOMBIA', 'Bancolombia')], max_length=20, null=True)),
                ('wompi_transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('wompi_reference', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('wompi_payment_link', models.URLField(blank=True, max_length=500, null=True)),
                ('wompi_checkout_url', models.URLField(blank=True, help_text='URL de checkout de Wompi', max_length=500, null=True)),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('payer_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=50, null=True)),
                ('user_type', models.CharField(blank=True, help_text='0: Persona Natural, 1: Persona Jurídica', max_length=20, null=True)),
                ('booking_date', models.DateField(blank=True, db_index=True, help_text='Fecha de la excursión', null=True)),
                ('total_participants', models.PositiveIntegerField(blank=True, default=1, help_text='Número total de participantes (incluyendo titular)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales de la reserva')),
                ('description', models.TextField(blank=True, help_text='Descripción del pago')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del pago en formato JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Fecha y hora de aprobación del pago', null=True)),
                ('ruta', models.ForeignKey(blank=True, help_text='Ruta asociada al pago', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='routes.rutasenderismo')),
                ('user', models.ForeignKey(help_text='Usuario que realiza el pago (titular de la reserva)', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Nombre completo del participante', max_length=200)),
                ('phone', models.CharField(help_text='Teléfono del participante', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email del participante (opcional)', max_length=254, null=True)),
                ('emergency_contact_name', models.CharField(help_text='Nombre del contacto de emergencia', max_length=200)),
                ('emergency_contact_phone', models.CharField(help_text='Teléfono del contacto de emergencia', max_length=20)),
                ('is_titular', models.BooleanField(default=False, help_text='Si es el titular de la reserva (quien paga)')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Orden del participante en la lista (1 = titular)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='payments.payment')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario si está registrado en la app', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'db_table': 'payment_participants',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='Tipo de evento (transaction.updated, etc.)', max_length=100)),
                ('transaction_id', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(help_text='Estado recibido en el webhook', max_length=50)),
                ('raw_payload', models.JSONField(help_text='Payload completo del webhook')),
                ('processed', models.BooleanField(default=False, help_text='Si el webhook fue procesado exitosamente')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si hubo problemas al procesar')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'db_table': 'payment_webhook_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_user_id_1b771c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['ruta', 'status'], name='payments_ruta_id_830599_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['wompi_transaction_id'], name='payments_wompi_t_259355_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_created_e3a130_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking_date'], name='payments_booking_3d177b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_status_426d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentparticipant',
            index=models.Index(fields=['payment', 'order'], name='payment_par_payment_22f2c6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentparticipant',
            index=models.Index(fields=['payment', 'is_titular'], name='payment_par_payment_dbb21d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentparticipant',
            unique_together={('payment', 'order')},
        ),
        migrations.AddIndex(
            model_name='paymentwebhooklog',
            index=models.Index(fields=['transaction_id', 'created_at'], name='payment_web_transac_f9f245_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhooklog',
            index=models.Index(fields=['processed', 'created_at'], name='payment_web_process_81d8c2_idx'),
        ),
    ]
